#!/bin/bash
#generates the table using tpcds.sql script in tpcds kit into database called tpcds (be careful about the paths and username!)
/opt/lampp/bin/mysql -uroot -p tpcds < ./tpcds/tools/tpcds.sql
#loading data (be careful about the paths and username!)
/opt/lampp/bin/mysql -uroot -p tpcds < /root/tpcds/tools/tmp/insertdata.sql
#create relations of the tables using tpcds_ri.sql script in tpcds kit (be careful about the paths and username!)
/opt/lampp/bin/mysql -uroot -p tpcds < /root/tpcds/tools/tpcds_ri.sql
